### ISSUE TITLE
Configuration options for logging

### ISSUE THREAD

**Issue by Derkades** [lucko/bytebin#11]
I'd like to run the docker container in read only mode. I could mount tmpfs in `/opt/bytebin/logs` but since docker handles logging anyway it makes more sense to disable it. Could you add some options/environment variables to disable or configure logging?

**Comment by lucko** [comment]
Sure..

#### docker-compose.yml
```yml
version: "3.8"

services:
  bytebin:
    image: ghcr.io/lucko/bytebin
    ports:
      - 3000:8080
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - data:/opt/bytebin/content
      - ./log4j2.xml:/opt/bytebin/log4j2.xml:ro
    environment:
      BYTEBIN_LOG4J_CONFIG: /opt/bytebin/log4j2.xml
      BYTEBIN_TMP_DIR: /tmp

volumes:
  data: {}
```

#### log4j2.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="warn">
    <Appenders>
        <Console name="Console">
            <PatternLayout pattern="%highlight{[%d{HH:mm:ss} %level]: %msg%n%xEx}"/>
        </Console>
    </Appenders>

    <Loggers>
        <Root level="info">
            <AppenderRef ref="Console"/>
        </Root>
    </Loggers>
</Configuration>
```

You could also disable logging completely by using a null appender.

Hope that helps :)
