### ISSUE TITLE
CORS Policy Error

### ISSUE THREAD

**Issue by RappyTV** [lucko/bytebin#25]
I always get this error no matter which container I call the API from: pastes.dev, spark, or luckperms api. (This screenshot is from [my pastes.dev instance](https://paste.rappytv.com))
![image](https://github.com/lucko/bytebin/assets/72705182/eeb5e79b-37ef-49b9-a200-b67658e999bb)
Here is my dockerfile:
```yml
version: "3.8"
services:
  bytebin:
    image: ghcr.io/lucko/bytebin
    volumes:
      - ./data:/opt/bytebin/content
    environment:
      BYTEBIN_MISC_KEYLENGTH: 8
      VIRTUAL_HOST: bytebin.rappytv.com
    ports:
      - 7102:8080
    restart: unless-stopped
networks: {}
```
